const config = window.SUPABASE_CONFIG || {};
let supabase = null;
let configError = '';
if (!String(config.url || '').trim() || !String(config.anonKey || '').trim()) configError = 'Configure admin/config.js with your Supabase URL and anon key.';
else if (!window.supabase?.createClient) configError = 'The Supabase client library did not load. Check your internet connection and reload.';
else { try { supabase = window.supabase.createClient(String(config.url).trim(), String(config.anonKey).trim()); } catch (error) { configError = 'The Supabase configuration is invalid. Check admin/config.js.'; } }
const $ = selector => document.querySelector(selector);
const setLoginStatus = (text, error = false) => { $('#loginStatus').textContent = text; $('#loginStatus').className = `status${error ? ' error' : ''}`; };
let currentRoute = 'dashboard';

function render(route) { currentRoute = route; document.querySelectorAll('.route').forEach(section => { section.hidden = section.id !== route; }); document.querySelectorAll('[data-route]').forEach(button => button.classList.toggle('active', button.dataset.route === route)); $('#pageTitle').textContent = route === 'keys' ? 'Activation Keys' : route === 'activity' ? 'Activity Logs' : route[0].toUpperCase() + route.slice(1); if (route === 'dashboard') loadDashboard(); if (route === 'keys') loadKeys(); if (route === 'activity') loadLogs(); if (route === 'customers') loadCustomers(); if (route === 'settings') loadSettings(); }
async function functionError(error, fallback) { if (error?.context?.status === 404) return new Error('Admin backend function is not deployed. Deploy admin-actions to the Supabase project configured in admin/config.js.'); try { const body = await error?.context?.json(); if (body?.error) return new Error(body.error); } catch {} return new Error(fallback); }
async function invoke(action, body = {}) { if (!supabase) throw new Error(configError || 'Supabase is unavailable.'); const { data, error } = await supabase.functions.invoke('admin-actions', { body: { action, ...body } }); if (error) throw await functionError(error, 'Admin backend request failed.'); return data; }
async function invokeFunction(name, body = {}) { if (!supabase) throw new Error(configError || 'Supabase is unavailable.'); const { data, error } = await supabase.functions.invoke(name, { body }); if (error) throw await functionError(error, 'Admin backend request failed.'); return data; }
function statCard(label, value) { return `<article class="stat"><span>${label}</span><strong>${value}</strong></article>`; }
async function loadDashboard() { const root = $('#dashboard'); root.innerHTML = '<p class="subtle">Loading dashboard...</p>'; try { const stats = await invoke('stats'); root.innerHTML = `<div class="stats">${statCard('Total Keys', stats.total)}${statCard('Active', stats.active)}${statCard('Expired', stats.expired)}${statCard('Suspended', stats.suspended)}${statCard('Lifetime', stats.lifetime)}</div><section class="panel"><div class="panel-head"><h2>License operations</h2><button class="button" data-create>+ Create Activation Key</button></div><p class="subtle">Server-authorized activation key lifecycle and audit controls.</p></section>`; root.querySelector('[data-create]').onclick = () => { render('keys'); setTimeout(showCreateForm, 0); }; } catch (error) { root.innerHTML = `<p class="status error">${error.message}</p>`; } }
function showCreateForm() { const root = $('#keys'); root.innerHTML = `<section class="panel"><div class="panel-head"><h2>Create Activation Key</h2><button class="button" data-back>View all keys</button></div><form id="createForm" class="form-grid"><label>Customer Name<input id="customerName" required></label><label>Customer Email<input id="customerEmail" type="email" required></label><label>License Type<select id="licenseType"><option value="time_limited">Time Limited</option><option value="lifetime">Lifetime</option></select></label><label id="expiryField">Expires At<input id="expiresAt" type="datetime-local" required></label><label>Notes<input id="notes"></label><div><button class="primary" type="submit">Generate Activation Key</button></div></form><p id="createStatus" class="status"></p><pre id="createdKey" hidden></pre></section>`; root.querySelector('[data-back]').onclick = loadKeys; $('#licenseType').onchange = event => { $('#expiryField').hidden = event.target.value === 'lifetime'; $('#expiresAt').required = event.target.value !== 'lifetime'; }; $('#createForm').onsubmit = createKey; }
async function createKey(event) { event.preventDefault(); const status = $('#createStatus'); status.textContent = 'Generating securely...'; try { const result = await invokeFunction('create-activation', { customerName: $('#customerName').value, customerEmail: $('#customerEmail').value, licenseType: $('#licenseType').value, expiresAt: $('#expiresAt').value ? new Date($('#expiresAt').value).toISOString() : null, notes: $('#notes').value }); status.textContent = 'Activation Key Created Successfully. Save it securely; it will not be displayed again.'; status.className = 'status ok'; const output = $('#createdKey'); output.hidden = false; output.innerHTML = `<code>${escapeHtml(result.activationKey)}</code><button class="button" id="copyCreatedKey" type="button">Copy Activation Key</button>`; $('#copyCreatedKey').onclick = async () => { await navigator.clipboard.writeText(result.activationKey); $('#copyCreatedKey').textContent = 'Copied'; }; } catch (error) { status.textContent = error.message || 'Could not create Activation Key.'; status.className = 'status error'; } }
async function loadKeys() { const root = $('#keys'); root.innerHTML = `<section class="panel"><div class="panel-head"><h2>Activation Keys</h2><button class="button" data-create>+ Create Activation Key</button></div><div class="filters"><input id="keySearch" placeholder="Search customer or identifier"><select id="keyStatus"><option value="">All statuses</option><option>active</option><option>expired</option><option>suspended</option><option>revoked</option></select><select id="keyType"><option value="">All licenses</option><option value="lifetime">Lifetime</option><option value="time_limited">Time Limited</option></select></div><div id="keysTable">Loading...</div></section>`; root.querySelector('[data-create]').onclick = showCreateForm; try { const result = await invoke('list', { offset: 0, limit: 100 }); const rows = result.data || []; const renderRows = () => { const search = root.querySelector('#keySearch'); const statusFilter = root.querySelector('#keyStatus'); const typeFilter = root.querySelector('#keyType'); const table = root.querySelector('#keysTable'); if (!search || !statusFilter || !typeFilter || !table) return; const query = search.value.toLowerCase(); const status = statusFilter.value; const type = typeFilter.value; const filtered = rows.filter(row => (!query || `${row.customer_name} ${row.customer_email} ${row.key_identifier}`.toLowerCase().includes(query)) && (!status || row.status === status) && (!type || row.license_type === type)); table.innerHTML = `<table><thead><tr><th>Customer</th><th>Key</th><th>License</th><th>Expires</th><th>Last Used</th><th>Status</th><th>Actions</th></tr></thead><tbody>${filtered.map(row => `<tr><td><strong>${escapeHtml(row.customer_name)}</strong><br>${escapeHtml(row.customer_email)}</td><td>${escapeHtml(row.key_identifier)}-••••••-••••-••••••</td><td>${row.license_type.replace('_', ' ')}</td><td>${row.expires_at ? new Date(row.expires_at).toLocaleDateString() : 'Lifetime'}</td><td>${row.last_used_at ? new Date(row.last_used_at).toLocaleString() : 'Never'}</td><td><span class="badge ${row.status}">${row.status}</span></td><td><button class="button" data-status="${row.id}" data-value="${row.status === 'suspended' ? 'active' : 'suspended'}">${row.status === 'suspended' ? 'Activate' : 'Suspend'}</button></td></tr>`).join('') || '<tr><td colspan="7">No matching Activation Keys.</td></tr>'}</tbody></table>`; root.querySelectorAll('[data-status]').forEach(button => button.onclick = () => setStatus(button.dataset.status, button.dataset.value)); }; ['keySearch', 'keyStatus', 'keyType'].forEach(id => { const control = root.querySelector(`#${id}`); if (control) control.oninput = renderRows; }); renderRows(); } catch (error) { const table = root.querySelector('#keysTable'); if (table) table.textContent = error.message; } }
async function setStatus(id, status) { if (!confirm(`Set this Activation Key to ${status}?`)) return; await invoke('set_status', { id, status }); loadKeys(); }
async function loadLogs() { const root = $('#activity'); root.innerHTML = '<section class="panel"><h2>Activity Logs</h2><div id="logs">Loading...</div></section>'; try { const result = await invoke('logs'); $('#logs').innerHTML = `<table><thead><tr><th>Action</th><th>Identifier</th><th>Date</th></tr></thead><tbody>${(result.data || []).map(row => `<tr><td>${escapeHtml(row.action)}</td><td>${escapeHtml(row.metadata?.key_identifier || row.activation_key_id || 'System')}</td><td>${new Date(row.created_at).toLocaleString()}</td></tr>`).join('')}</tbody></table>`; } catch (error) { $('#logs').textContent = error.message; } }
function loadCustomers() { $('#customers').innerHTML = '<section class="panel"><h2>Customers</h2><p class="subtle">Customer records are managed through Activation Keys. Use the Activation Keys view to search and manage customer licenses.</p></section>'; }
function loadSettings() { $('#settings').innerHTML = '<section class="panel"><h2>Admin Settings</h2><p class="subtle">Private service credentials are never displayed here.</p><form id="passwordForm"><label>New password<input id="newPassword" type="password" minlength="8" required></label><button class="primary" type="submit">Change Password</button><p id="passwordStatus" class="status"></p></form></section>'; $('#passwordForm').onsubmit = async event => { event.preventDefault(); const { error } = await supabase.auth.updateUser({ password: $('#newPassword').value }); $('#passwordStatus').textContent = error ? 'Could not change password.' : 'Password changed successfully.'; $('#passwordStatus').className = `status${error ? ' error' : ' ok'}`; }; }
function escapeHtml(value) { return String(value || '').replace(/[&<>'"]/g, character => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[character])); }

document.querySelectorAll('[data-route]').forEach(button => button.onclick = () => render(button.dataset.route));
$('#loginForm').onsubmit = async event => { event.preventDefault(); if (!supabase) { setLoginStatus(configError || 'Supabase is unavailable.', true); return; } setLoginStatus('Signing in...'); const { data, error } = await supabase.auth.signInWithPassword({ email: $('#email').value, password: $('#password').value }); if (error || !data.user) { setLoginStatus('Unable to sign in with those credentials.', true); return; } showApp(data.user); };
async function showApp(user) { if (!supabase || !user) return; const { data: profile, error } = await supabase.from('profiles').select('role').eq('id', user.id).single(); if (error || profile?.role !== 'admin') { await supabase.auth.signOut(); $('#appView').hidden = true; $('#loginView').hidden = false; setLoginStatus('This account does not have administrator access.', true); return; } $('#loginView').hidden = true; $('#appView').hidden = false; $('#adminEmail').textContent = user.email || ''; render(currentRoute); }
$('#logout').onclick = async () => { await supabase?.auth.signOut(); $('#appView').hidden = true; $('#loginView').hidden = false; };
if (supabase) supabase.auth.getSession().then(({ data }) => { if (data.session?.user) showApp(data.session.user); });