import { corsHeaders, json, requireAdmin } from '../_shared/auth.ts';
Deno.serve(async request => {
  if (request.method === 'OPTIONS') return new Response('ok', { headers: corsHeaders });
  try {
    const { client, profile } = await requireAdmin(request); const input = await request.json(); const action = String(input.action || '');
    if (action === 'list') { const offset = Number(input.offset || 0); const limit = Math.min(100, Math.max(1, Number(input.limit || 50))); const { data, error } = await client.from('activation_keys').select('id, key_identifier, customer_name, customer_email, license_type, created_at, expires_at, last_activated_at, last_used_at, activation_count, status, notes').order('created_at', { ascending: false }).range(offset, offset + limit - 1); if (error) throw error; return json({ data, offset, limit }); }
    if (action === 'stats') { const { data } = await client.from('activation_keys').select('license_type, status, expires_at'); const rows = data || []; return json({ total: rows.length, active: rows.filter(row => row.status === 'active').length, expired: rows.filter(row => row.status === 'expired').length, suspended: rows.filter(row => row.status === 'suspended').length, revoked: rows.filter(row => row.status === 'revoked').length, lifetime: rows.filter(row => row.license_type === 'lifetime').length }); }
    if (action === 'logs') { const { data, error } = await client.from('audit_logs').select('id, admin_id, action, activation_key_id, metadata, created_at').order('created_at', { ascending: false }).limit(100); if (error) throw error; return json({ data }); }
    if (action === 'set_status') { const allowed = ['active', 'suspended', 'revoked']; if (!allowed.includes(input.status)) return json({ error: 'Invalid status.' }, 400); const updates = { status: input.status, suspended_at: input.status === 'suspended' ? new Date().toISOString() : null, revoked_at: input.status === 'revoked' ? new Date().toISOString() : null, updated_by: profile.id }; const { error } = await client.from('activation_keys').update(updates).eq('id', input.id); if (error) throw error; await client.from('audit_logs').insert({ admin_id: profile.id, action: `activation_key_${input.status}`, activation_key_id: input.id, metadata: {} }); return json({ ok: true }); }
    if (action === 'delete') { const { error } = await client.from('activation_keys').delete().eq('id', input.id); if (error) throw error; await client.from('audit_logs').insert({ admin_id: profile.id, action: 'activation_key_deleted', metadata: { activation_key_id: input.id } }); return json({ ok: true }); }
    return json({ error: 'Unknown admin action.' }, 400);
  } catch (error) { if (error.message === 'Unauthorized') return json({ error: 'Unauthorized' }, 401); if (error.message === 'Forbidden') return json({ error: 'Forbidden' }, 403); return json({ error: 'Admin backend is unavailable. Check Edge Function secrets and database deployment.' }, 500); }
});